In [1]:
import numpy as np 
import  pandas as pd
import tensorflow as tf
from keras.layers import Dense,Input, MaxPool2D , Conv2D , Flatten
from keras.models import Sequential
from keras.losses import SparseCategoricalCrossentropy 
from keras.optimizers import Adam
from sklearn.metrics import accuracy_score


from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

np.random.seed(44)
tf.random.set_seed(44)

#### Data Visualisation

In [2]:
df = pd.read_csv('./train.csv')
print('traing data fraim first values : ')
df.head()


traing data fraim first values : 


label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [3]:
print('training data frame shape: ',df.shape)
X_train = df.iloc[:,1:]
print("X_train.shape : ",X_train.shape)
print('first 5 rows of X_train: ')
X_train[:5]

training data frame shape:  (42000, 785)
X_train.shape :  (42000, 784)
first 5 rows of X_train: 


pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 784 columns]

In [4]:
y_train=df.loc[:,'label']
print("y_train.shape : ",y_train.shape,'\n\n')
print('first 5 rows of y_train: ')
y_train[:5]

y_train.shape :  (42000,) 


first 5 rows of y_train: 


0    1
1    0
2    1
3    4
4    0
Name: label, dtype: int64

#### Spliting Data 

In [5]:
X_train,X_test,y_train,y_test = train_test_split(X_train,y_train,test_size=0.2,random_state=44, shuffle=True)
print("X_train.shape : ",X_train.shape)
print("y_train.shape : ",y_train.shape,'\n\n')
print("X_test.shape : ",X_test.shape)
print("y_test.shape : ",y_test.shape)



X_train = np.array(X_train)
X_test = np.array(X_test)
y_train = np.array(y_train)
y_test = np.array(y_test)

X_train.shape :  (33600, 784)
y_train.shape :  (33600,) 


X_test.shape :  (8400, 784)
y_test.shape :  (8400,)


#### Feature Scalling

In [6]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
print(X_train.shape)
print(X_train_scaled.shape)
X_test_scaled = scaler.transform(X_test)

(33600, 784)
(33600, 784)


Neural network model 

In [7]:
model =  Sequential([
    Input(shape=(X_train.shape[1])),
    Dense(units=X_train.shape[1],activation='relu',name='layer1'),
    Dense(units=64,activation='relu',name='layer2'),
    Dense(units=32,activation='relu',name='layer3'),
    Dense(units=32,activation='relu',name='layer4'),
    Dense(units=32,activation='relu',name='layer5'),
    Dense(units=16,activation='relu',name='layer6'),
    Dense(units=16,activation='relu',name='layer7'),
    Dense(units=16,activation='relu',name='layer8'),
    Dense(units=14,activation='relu',name='layer9'),
    Dense(units=10,activation='linear',name='output_layer'),
])



In [8]:

model.compile(
    loss=SparseCategoricalCrossentropy(from_logits=True),
    optimizer=Adam(learning_rate=0.001)
)

#### Traing data 

In [9]:
model.fit(X_train_scaled,y_train)


1050/1050 [==============================] - 7s 6ms/step - loss: 0.4717


Predictions :

In [10]:
y_train_pred = model.predict(X_train_scaled)
y_test_pred = model.predict(X_test_scaled)



263/263 [==============================] - 1s 3ms/step


#### Convert predicted values into class labels

In [11]:
# Convert predicted values into class labels for the training set
y_train_labels = np.argmax(y_train_pred, axis=1)

# Convert predicted values into class labels for the test set
y_test_labels = np.argmax(y_test_pred, axis=1)

print(y_train_labels)
print(y_test_labels)



[5 1 1 ... 0 6 6]
[9 5 3 ... 7 7 6]


Cumputing Accurancy

In [12]:

print('accuracy_score X_train : ',accuracy_score(y_true=y_train,y_pred=y_train_labels))
print('accuracy_score X_test : ',accuracy_score(y_true=y_test,y_pred=y_test_labels))

accuracy_score X_train :  0.95
accuracy_score X_test :  0.9366666666666666


#### Submit Predections 

In [13]:
submet=pd.read_csv('./sample_submission.csv')
submet

ImageId  Label
0            1      2
1            2      0
2            3      9
3            4      9
4            5      3
...        ...    ...
27995    27996      9
27996    27997      7
27997    27998      3
27998    27999      9
27999    28000      2

[28000 rows x 2 columns]

In [14]:
X_sub = pd.read_csv('./test.csv')
X_sub= np.array(X_sub)

scaler.transform(X_sub)
y_sub_pred = model.predict(X_sub)
y_sub_labels= np.argmax(y_sub_pred,axis=1)
print(y_sub_labels)

875/875 [==============================] - 3s 4ms/step
[2 0 8 ... 3 9 2]


In [15]:
#y_test_labels = [int(label) for label in y_test_labels]

submet['Label']=y_sub_labels
submet

ImageId  Label
0            1      2
1            2      0
2            3      8
3            4      7
4            5      3
...        ...    ...
27995    27996      9
27996    27997      7
27997    27998      3
27998    27999      9
27999    28000      2

[28000 rows x 2 columns]

In [16]:
# Save the modified DataFrame back to the CSV file
submet.to_csv('./sample_submission.csv', index=False)

# Using Convlayers


In [17]:
image_shape = (28,28,1)
train_n_images = X_train_scaled.shape[0]

X_train_scaled= tf.reshape(X_train_scaled, (train_n_images, image_shape[0], image_shape[1], image_shape[2]))

X_test=np.array(X_test)
test_n_images = X_test_scaled.shape[0]
X_test_scaled= tf.reshape(X_test_scaled, (test_n_images,image_shape[0], image_shape[1], image_shape[2]))

print(X_train_scaled.shape)
X_test_scaled.shape

(33600, 28, 28, 1)


TensorShape([8400, 28, 28, 1])

In [18]:
modelConv =  Sequential([
    Input(shape =image_shape , name='inputConv'),
    Conv2D(filters=64,kernel_size=3,padding= "valid",activation='relu',name='ConvLayer1'),
    MaxPool2D((2,2),name='poolLayer1'),

    Conv2D(filters=32,kernel_size=3,padding= "valid",activation='relu',name='ConvLayer2'),
    MaxPool2D((2,2),name='poolLayer2'),

    Conv2D(filters=16,kernel_size=3,padding= "valid",activation='relu',name='ConvLayer3'),
    MaxPool2D((2,2),name='poolLayer3'),
    
    Conv2D(filters=8,kernel_size=3,padding= "same",activation='relu',name='ConvLayer4'),
    MaxPool2D((2,2),name='poolLayer4'),

    Conv2D(filters=2,kernel_size=3,padding= "valid",activation='relu',name='ConvLayer5'),
    MaxPool2D((2,2),name='poolLayer5'),

    Flatten(),

    Dense(units=64,activation='relu',name='FC'),
    Dense(units=10,activation='linear',name='output_layer'),
],name = 'ConvSeqModel')


### Train the conv model : 

In [19]:
modelConv.compile(loss=SparseCategoricalCrossentropy(from_logits=True),
                  optimizer=Adam(learning_rate=0.01))
print(X_train_scaled.shape)
print(X_train.shape)
print(y_train.shape)
modelConv.fit(X_train_scaled,y_train)


(33600, 28, 28, 1)
(33600, 784)
(33600,)


1050/1050 [==============================] - 61s 58ms/step - loss: 0.8622


#### Preedictions 



In [20]:
y_train_pred = modelConv.predict(X_train_scaled)
y_test_pred = modelConv.predict(X_test_scaled)

# Convert predicted values into class labels for the training set
y_train_labels = np.argmax(y_train_pred, axis=1)

# Convert predicted values into class labels for the test set
y_test_labels = np.argmax(y_test_pred, axis=1)

print(y_train_labels)
print(y_test_labels)


263/263 [==============================] - 1s 4ms/step
[5 1 1 ... 0 0 6]
[9 9 2 ... 7 7 6]


#### Computing accurancy


In [26]:
print(y_test_labels)
y_test

[9 9 2 ... 7 7 6]


array([9, 7, 2, ..., 7, 7, 6], dtype=int64)

In [22]:

print('accuracy_score X_train : ',accuracy_score(y_true=y_train,y_pred=y_train_labels))
print('accuracy_score X_test : ',accuracy_score(y_true=y_test,y_pred=y_test_labels))

accuracy_score X_train :  0.8461607142857143
accuracy_score X_test :  0.8351190476190476
